meta_product_name: "Wedding Dressing"
meta_title: "Wedding Dressing - L'app qui vous habille pour les grandes occasions"
meta_description: "Vous avez une tenue mais n'êtes pas sure ? Demandez un avis, un conseil ou l'accessoire qu'il vous manque"
meta_image: "beyonce.jpg"                           # Une image dans votre dossier app/assets/images/
