meta_product_name: "Swaplab"
meta_title: "Swaplab - Partagez votre garde-robe avec vos copines !"
meta_description: "Vous ne savez plus quoi faire d'un vêtement ? Donnez-le ou vendez-le à petit prix à votre copine qui l'adore !"
meta_image: "home-banner.jpg"                           # Une image dans votre dossier app/assets/images/
